# Generated by Django 4.0.1 on 2022-01-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_image_delete_imageupl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
